service: Hana-Automation

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.11

layers:
  FirstLayer:
    path: /
    compatibleRuntimes: 
      - python3.11
    description: "dependencies"
