service: Hana-Automation

plugins:
  - serverless-python-requirements
  - serverless-lambda-layers

provider:
  name: aws
  runtime: python3.11

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true

layers:
  pythonRequirements:
    path: layer

package:
  exclude:
    - "!node_modules/**"
    - "!yarn.lock"
    - ".serverless"
